fai_path: example-configs/Otsh_v1.0-nz-arg-etc/Otsh_v1.0_genomic.fna.fai
scaff_group_path: example-configs/Otsh_v1.0-nz-arg-etc/scaffs_chrom_only_with28.tsv


bcf:
 testy:
  path: "ls example-configs/Otsh_v1.0-nz-arg-etc/resources/pass-maf-0.01.bcf"
   sample_subsets:
    all:
     path: sample_subsets/sample_list.txt

 # cali_only:
   # path: "example-configs/Otsh_v1.0-nz-arg-etc/resources/ca_only.vcf.gz"
    #sample_subsets:
     # all:
      #  path: "example-configs/Otsh_v1.0-nz-arg-etc/resources/ca_only.txt"
  #ca_arg_only:
   # path: "example-configs/Otsh_v1.0-nz-arg-etc/resources/ca_arg_only.vcf.gz"
    #sample_subsets:
     # all:
      #  path: "example-configs/Otsh_v1.0-nz-arg-etc/resources/ca_arg_samples_list.txt"
      #arg_only: 
       # path: "example-configs/Otsh_v1.0-nz-arg-etc/resources/arg_only.txt"
    
  #ca_nz_only:
   # path: "example-configs/Otsh_v1.0-nz-arg-etc/resources/ca_nz_only.vcf.gz"
    #sample_subsets:
     # all:
      #  path: "example-configs/Otsh_v1.0-nz-arg-etc/sample_lists/ca_nz_samples_list.txt"
       # nz_only: 
        #path: "example-configs/Otsh_v1.0-nz-arg-etc/resources/nz_only.txt"
      #cv_and_south:
     #   path: "example-configs/Otsh_v1.0-nz-arg-etc/sample_lists/cv-and-south-hemi.txt"
      #  dotsample: "example-configs/Otsh_v1.0-nz-arg-etc/dot-samples/cv-and-south-hemi.tsv"
       # ybin: "example-configs/Otsh_v1.0-nz-arg-etc/ybins/cv-and-south-hemi.txt"




bcftools_opts:
  snps05: -v snps -m 2 -M 2 -i 'FILTER="PASS" && MAF >= 0.05'


pcangsd:
  url: https://github.com/eriqande/pcangsd.git
  version: 705ca4c19630ed9c2dd254b0bfd528b8ee25d5c0
ngsAdmix:
  url: https://github.com/aalbrechtsen/NGSadmix.git
  version: a5cde0502ac1e1cfce994bc9fd72ef1813c262b6
evalAdmix:
  url: https://github.com/hmoyle/evalAdmix
  version: 89ba80529be6d96ca6224434bab2fdf26acedd5f

main_params:
  standard:
    bcf: testy
    filt: snps05
    thin_spec: "0_0"
    maf: 0.05

#main_params:
   # cali:
    #bcf: cali_only
    #filt: snps05
    #thin_spec: "0_0"
    #maf: 0.05
  #ca_arg:
   # bcf: ca_arg_only
    #filt: snps05
    #thin_spec: "0_0"
    #maf: 0.05
  #ca_nz:
   # bcf: ca_nz_only
    #filt: snps05
    #thin_spec: "0_0"
    #maf: 0.05



params:
  ngsadmix:
    four_for_ten:
      reps: 4
      kvals: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  evaladmix:
    four_for_ten:
      reps: 4
      kvals: [2, 3, 4, 5, 6, 7, 8, 9, 10]

targets:
  ngsadmix:
    - ["standard", "all", "four_for_ten"]
  evaladmix:
    - ["standard", "all", "four_for_ten"]

#targets:
  #ngsadmix:
   # - ["cali", "all", "four_for_ten"]
    #- ["ca_arg", "all", "no_frills"]
    #- ["ca_nz", "all", "no_frills"]
  #evaladmix:
   # - ["cali", "all", "four_for_ten"]
    #- ["ca_arg", "all", "no_frills"]
    #- ["ca_nz", "all", "no_frills"]

