fai_path: resources/genome.fasta.fai
scaff_group_path: resources/scaffold_groups.tsv


bcf:
  testy:
    path: "resources/pass-maf-0.01.bcf"
    sample_subsets:
      all:
        path: sample_subsets/sample_list.txt



bcftools_opts:
  snps05: -v snps -m 2 -M 2 -i 'FILTER="PASS" && MAF >= 0.05'


pcangsd:
  url: https://github.com/eriqande/pcangsd.git
  version: 705ca4c19630ed9c2dd254b0bfd528b8ee25d5c0
ngsAdmix:
  url: https://github.com/aalbrechtsen/NGSadmix.git
  version: a5cde0502ac1e1cfce994bc9fd72ef1813c262b6
evalAdmix:
  url: https://github.com/hmoyle/evalAdmix
  version: 89ba80529be6d96ca6224434bab2fdf26acedd5f


main_params:
  standard:
    bcf: testy
    filt: snps05
    thin_spec: "0_0"
    maf: 0.05



params:
  ngsadmix:
    four_for_ten:
      reps: 4
      kvals: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  evaladmix:
    four_for_ten:
      reps: 4
      kvals: [2, 3, 4, 5, 6, 7, 8, 9, 10]


targets:
  ngsadmix:
    - ["standard", "all", "four_for_ten"]
  evaladmix:
    - ["standard", "all", "four_for_ten"]

