## This is the config file that determnines what analyses will
## be run on which sample subset from which parent BCF

## This is the config file that determnines what analyses will
## be run on which sample subset from which parent BCF


#### MODULES SECTION

# This is what you would use on Alpine
#Rmodule: "R/4.2.2"

# This is what you would use on SEDNA
Rmodule: "R/4.0.3"


#### DEFINITIONS SECTIONS #####

# every BCF file used here must correspond to the same
# reference genome and thus to the same scaffold groups file.
# These are identified here:
fai_path: example-configs/arg-nz-ca-chinook/data/genome.fasta.fai
scaff_group_path: example-configs/arg-nz-ca-chinook/data/scaffold_group_chroms_only.tsv


# this is the short name and the path to the BCF file that will be used
# the key here (testy) corresponds to wildcard {bcf_id}.  The sample subsets
# should, of course, correspond to a particular
# bcf file, so they go here.  If there are meta data files for association
# studies in ANGSD, these go here as the dotsample.
bcf:
  main:
    path: "example-configs/arg-nz-ca-chinook/data/all.bcf"
    sample_subsets:
      all:
       path: example-configs/arg-nz-ca-chinook/sample_subsets/samples_list_CAxArg.txt     #  all  fish
       dotsample: example-configs/arg-nz-ca-chinook/data/dot-samples-CAxArg.tsv
    #  ca_arg:
      # path: example-configs/arg-nz-ca-chinook/sample_subsets/ca_arg_samples_list.txt #just argentina vs ca
    #  ca_nz:
      #  path: example-configs/arg-nz-ca-chinook/sample_subsets/ca_nz_samples_list.txt  #just nz vs ca   
     # males:
       # path: .test/sample_subsets/males.txt    # just the males
       # dotsample: .test/data/dot-samples-males.tsv
      #females:
       # path: .test/sample_subsets/females.txt  # just the females
       # dotsample: .test/data/dot-samples-females.tsv 


# same thing here, we can define different sets of bcftools filters
# that we might want to use, and we give them nicknames. The 
# nicknames/keys here correspond to wildcard 
bcftools_opts:
  snps05: -v snps -m 2 -M 2 -i 'FILTER="PASS" && MAF >= 0.05'


#### SETTING SECTIONS #####

pcangsd:
  url: https://github.com/eriqande/pcangsd.git
  version: 705ca4c19630ed9c2dd254b0bfd528b8ee25d5c0
ngsAdmix:
  url: https://github.com/aalbrechtsen/NGSadmix.git
  version: a5cde0502ac1e1cfce994bc9fd72ef1813c262b6




#### PARAMETERS SECTION
# Here we can give some short names for different sets of parameters
# that we will use later for particular ultimate targets

# these are all the standard parameters in the file paths
main_params:
  standard:
    bcf: main
    filt: snps05
    thin_spec: "0_0"
    maf: 0.05
 
    
# Here we provide different sets of parameters for particular
# analyses.
params:
 # do_asso:
  #  age_cohort_4PCs:
   #   angsd_opts: " -doMaf 4 -doAsso 4 "
    #  whichPhe: " age "
     # whichCov: " cohort,PC-1,PC-2,PC-3,PC-4 "
  ngsadmix:
      eight_for_eight:
        reps: 8
        kvals: [1, 2, 3, 4, 5, 6,8]



#### TARGETS SECTION

# here we have a shorthand for describing target outputs.
# Each output is defined by a triple: [A, B, C] that lives under
# a heading which says which kind of analysis is desired.
# where 
#   - A is a nickname from main_params
#   - B is a nickname for a subsample that is appropriate to the BCF in A
#   - C is a nickname for the parameters defined in params for the particular analysis
#
# The idea here is that each of these triples can be used to define a file name
# or possibly multiple filenames.

targets:
  #do_asso:
   # - ["standard", "all", "age_cohort_4PCs"]
    #- ["standard", "males", "age_cohort_4PCs"]
    #- ["standard", "females", "age_cohort_4PCs"]
  #beagle_gl: # this is here in case you just want to 
   # - ["standard", "males", "dummy"]
  ngsadmix:
    - ["standard", "all", "eight_for_eight"]
  #  - ["standard", "ca_arg", "four_for_five"]
  #  - ["standard","ca_nz", "four_for_five"]